apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels: 
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "gabrieldpadua21/server-go:v7"
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: goserver-env
                  key: NAME

            - name: COLOR
              valueFrom:
                configMapKeyRef:
                  name: goserver-env
                  key: COLOR
